# fly.toml app configuration file generated for gm-certbot on 2023-08-05T20:10:49+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gm-certbot"
primary_region = "sin"

[build]

[[services]]
  internal_port = 8080
  protocol = "http"
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

  [[services.ports]]
    handlers = ["proxy_proto"]
    port = 80
    force_https = false

  [[services.ports]]
    handlers = ["proxy_proto"]
    port = 443
    force_https = false
