# fly.toml app configuration file generated for gm-certbot on 2023-08-05T20:10:49+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gm-certbot"
primary_region = "sin"

[build]

[[services]]
  internal_port = 80
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

[[services]]
  internal_port = 443
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

# [http_service]
#   internal_port = 80
#   force_https = false
#   auto_stop_machines = true
#   auto_start_machines = true
#   min_machines_running = 0
#   processes = ["app"]
