# fly.toml app configuration file generated for gm-certbot on 2023-08-05T20:10:49+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dailyoops-gemini-mirror"
primary_region = "sin"

[build]

[build.args]
BUCKET_NAME="dailyoops-gemini"

[[services]]
  internal_port = 1965
  protocol = "tcp"

  [[services.ports]]
    port = "1965"
