name: Deploy

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.119.0'
          # extended: true

      - uses: actions/setup-go@v5
      - name: install missing dependencies
        run: |
          sudo apt install -y scdoc
      - name: Setup and install hut CLI
        run: |
          git clone https://git.sr.ht/~xenrox/hut /tmp/hut
          cd /tmp/hut
          make && sudo make install
          # setup hut config
          mkdir -p $XDG_CONFIG_HOME/hut
          echo > $XDG_CONFIG_HOME/hut/config <<EOF
            instance "sr.ht" {
              access-token "$HUT_ACCESS_TOKEN"
            }
          EOF

      - name: install gemgen
        run: |
          git clone https://git.sr.ht/~kota/gemgen /tmp/gemgen
          cd /tmp/gemgen
          sudo make install

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install


      - name: Build
        run: pnpm run build

      - name: Build hugo
        run: hugo --minify

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Deploy
        run: |
          cd ${{ github.workspace }}
          ./scripts/hut-publish
